version: '3.4'
services:
  web:
    build: .
    command: /bin/bash -c "rm -f /tmp/server.pid && bin/rails server -b 0.0.0.0 -P /tmp/server.pid"
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
  bundle_cache:
