default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  user: postgres
  password:

development:
  <<: *default
  database: backend_course_dev

test:
  <<: *default
  database: backend_course_test

